# Generated by Django 5.0.4 on 2024-04-22 11:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_alter_authcodemodel_date_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcodemodel',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authcodemodel',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 18, 38, 28, 522501)),
        ),
    ]
