# Generated by Django 5.0.4 on 2024-04-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_remove_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
