# Generated by Django 5.0.4 on 2024-04-23 07:37

import datetime
import referral.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_alter_authcodemodel_date_ended_alter_user_inviter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcodemodel',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 14, 42, 4, 393866)),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=referral.models.generate_auth_code, max_length=6),
        ),
    ]
