# Generated by Django 5.0.4 on 2024-04-24 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_alter_authcodemodel_date_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authcodemodel',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 17, 1, 43, 39204)),
        ),
    ]
