# Generated by Django 5.0.4 on 2024-04-22 15:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_alter_authcodemodel_date_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcodemodel',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='authcodemodel',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 22, 38, 13, 226232)),
        ),
        migrations.AlterField(
            model_name='authcodemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
