# Generated by Django 5.0.4 on 2024-04-22 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0005_alter_authcodemodel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcodemodel',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='authcodemodel',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 22, 41, 25, 664470)),
        ),
    ]
