# Generated by Django 5.0.4 on 2024-04-23 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_alter_authcodemodel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcodemodel',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 6, 46, 8, 886020)),
        ),
    ]
